# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Build CI

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [gcc]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y libgtkmm-3.0-dev libcurl4-gnutls-dev libyajl-dev valgrind
    - uses: actions/checkout@v4
    - run: make
    - run: sudo make install
    - run: which samrewritten
    - run: cd package && ./build_appimage.sh
    - name: Upload artifact
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: SamRewritten
        automatic_release_tag: continuous
        prerelease: false
        files: |
          package/Sam*.AppImage
